// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUserFieldNames          = builder.RawFieldNames(&TUser{})
	tUserRows                = strings.Join(tUserFieldNames, ",")
	tUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tUserRowsWithPlaceHolder = strings.Join(stringx.Remove(tUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tUserModel interface {
		Insert(ctx context.Context, data *TUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUser, error)
		Update(ctx context.Context, data *TUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TUser struct {
		Id         int64     `db:"id"`          // 用户id，自增主键
		Username   string    `db:"username"`    // 账号
		Password   string    `db:"password"`    // 密码，加密存储
		Salt       string    `db:"salt"`        // uuid，密码MD5加密
		NickName   string    `db:"nick_name"`   // 昵称
		Avatar     string    `db:"avatar"`      // 头像url
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
	}
)

func newTUserModel(conn sqlx.SqlConn) *defaultTUserModel {
	return &defaultTUserModel{
		conn:  conn,
		table: "`t_user`",
	}
}

func (m *defaultTUserModel) withSession(session sqlx.Session) *defaultTUserModel {
	return &defaultTUserModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`t_user`",
	}
}

func (m *defaultTUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTUserModel) FindOne(ctx context.Context, id int64) (*TUser, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserRows, m.table)
	var resp TUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) Insert(ctx context.Context, data *TUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, tUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Salt, data.NickName, data.Avatar)
	return ret, err
}

func (m *defaultTUserModel) Update(ctx context.Context, data *TUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Salt, data.NickName, data.Avatar, data.Id)
	return err
}

func (m *defaultTUserModel) tableName() string {
	return m.table
}
