// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"Thinkphoto/server/user/rpc/internal/logic"
	"Thinkphoto/server/user/rpc/internal/svc"
	"Thinkphoto/server/user/rpc/pb/service"
	"context"


)

type UserServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *service.RegisterRequest) (*service.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) FindById(ctx context.Context, in *service.FindByIdRequest) (*service.FindByIdResponse, error) {
	l := logic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

func (s *UserServer) FindByUserName(ctx context.Context, in *service.FindByUserNameRequest) (*service.FindByUserNameResponse, error) {
	l := logic.NewFindByUserNameLogic(ctx, s.svcCtx)
	return l.FindByUserName(in)
}
