// Code generated by goctl. DO NOT EDIT.
// Source: zinc.proto

package server

import (
	"Thinkphoto/server/Zinc/internal/logic"
	"Thinkphoto/server/Zinc/internal/svc"
	"Thinkphoto/server/Zinc/pb/zinc"
	"context"


)

type ZincSearchServer struct {
	svcCtx *svc.ServiceContext
	zinc.UnimplementedZincSearchServer
}

func NewZincSearchServer(svcCtx *svc.ServiceContext) *ZincSearchServer {
	return &ZincSearchServer{
		svcCtx: svcCtx,
	}
}

func (s *ZincSearchServer) Search(ctx context.Context, in *zinc.SearchRequest) (*zinc.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

func (s *ZincSearchServer) Delete(ctx context.Context, in *zinc.DeleteDocRequest) (*zinc.Response, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *ZincSearchServer) Update(ctx context.Context, in *zinc.UpdateDocRequest) (*zinc.Response, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *ZincSearchServer) Doc(ctx context.Context, in *zinc.Doc) (*zinc.Response, error) {
	l := logic.NewDocLogic(ctx, s.svcCtx)
	return l.Doc(in)
}
