// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likeCountFieldNames          = builder.RawFieldNames(&LikeCount{})
	likeCountRows                = strings.Join(likeCountFieldNames, ",")
	likeCountRowsExpectAutoSet   = strings.Join(stringx.Remove(likeCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	likeCountRowsWithPlaceHolder = strings.Join(stringx.Remove(likeCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	likeCountModel interface {
		Insert(ctx context.Context, data *LikeCount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LikeCount, error)
		Update(ctx context.Context, data *LikeCount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLikeCountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LikeCount struct {
		Id         int64     `db:"id"`          // 主键ID
		LinkingId  int64     `db:"linking_id"`  // 点赞对象id
		LikeNum    int64     `db:"like_num"`    // 点赞数
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
	}
)

func newLikeCountModel(conn sqlx.SqlConn) *defaultLikeCountModel {
	return &defaultLikeCountModel{
		conn:  conn,
		table: "`like_count`",
	}
}

func (m *defaultLikeCountModel) withSession(session sqlx.Session) *defaultLikeCountModel {
	return &defaultLikeCountModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`like_count`",
	}
}

func (m *defaultLikeCountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLikeCountModel) FindOne(ctx context.Context, id int64) (*LikeCount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", likeCountRows, m.table)
	var resp LikeCount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeCountModel) Insert(ctx context.Context, data *LikeCount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, likeCountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LinkingId, data.LikeNum)
	return ret, err
}

func (m *defaultLikeCountModel) Update(ctx context.Context, data *LikeCount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likeCountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LinkingId, data.LikeNum, data.Id)
	return err
}

func (m *defaultLikeCountModel) tableName() string {
	return m.table
}
