// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Thinkphoto/server/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: getVideoInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/followinglist",
				Handler: getFollowinglLstHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/followerlist",
				Handler: FollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publishAvatar",
				Handler: PublishAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: followHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/name",
				Handler: nameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user"),
	)
}
